"""
PineScript compiler — transforms builder-generated PineScript into a
``TransformedStrategy`` with a vectorized ``compute()`` callable.

Usage::

    from backtest.pine import transform_pinescript

    strategy = transform_pinescript(open("macd.pine").read())
    long_e, long_x, short_e, short_x = strategy.compute(df, params)
"""

from ..strategy import TransformedStrategy
from .tokens import Tokenizer
from .parser import Parser
from .codegen import CodeGenerator


def transform_pinescript(code: str) -> TransformedStrategy:
    """
    Compile PineScript source into a ``TransformedStrategy``.

    Parameters
    ----------
    code : str
        PineScript v6 source (as generated by the 4pass strategy builder).

    Returns
    -------
    TransformedStrategy
        Compiled strategy with ``compute(df, params)`` callable.
    """
    tokens = Tokenizer(code).tokenize()
    ast = Parser(tokens).parse()
    return CodeGenerator(ast, source=code).generate()
